language: general

services:
  - docker

before_install:
  - docker pull acidgenomics/rnaseq
  - docker images

script:
  - docker run -ti --user="bioc" --volume="${PWD}:/DESeqAnalysis" --workdir="/DESeqAnalysis" acidgenomics/rnaseq Rscript -e 'source("travis-docker.R")'

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
